name: Ryujinx AppImage

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: AppImage / Setup
      run: |
        sudo apt update
        sudo apt install libfuse2 desktop-file-utils zsync
    - name: AppImage / Build
      run: ./build.sh
    - name: AppImage / Version
      if: ${{ hashFiles('dist/') != '' }}
      id: version
      run: cat "./dist/version" >> "$GITHUB_OUTPUT"
    - name: Artifact / Upload
      if: ${{ hashFiles('dist/') != '' }}
      uses: actions/upload-artifact@v4
      with:
        name: Ryujinx-x86_64.AppImage
        path: 'dist'

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    if: ${{needs.build.outputs.version != ''}}
    steps:
    - name: Artifact / Download
      uses: actions/download-artifact@v4
      with:
        name: Ryujinx-x86_64.AppImage
    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      env:
        APPIMAGE_VERSION: ${{needs.build.outputs.version}}
      with:
        title: ${{ env.APPIMAGE_VERSION }}
        automatic_release_tag: ${{ env.APPIMAGE_VERSION }}
        prerelease: false
        draft: false
        files: |
          *.AppImage
          *.AppImage.zsync
        repo_token: ${{ secrets.GITHUB_TOKEN }}
